sudo: false
language: node_js
branches:
  only:
  - premaster
node_js:
- 'stable'
before_script:
- git config --global user.email "greybax@gmail.com"
- git config --global user.name "Aleksandr Filatov"
- git remote rm origin
- git remote add origin https://greybax:${GH_TOKEN}@github.com/greybax/iamstarkov.github.io.git
script: npm run deploy
