name: Node.js CI

on:
  push:
    branches: [ premaster ]
  pull_request:
    branches: [ premaster ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use Node.js 20+ to support `with { type: 'json' }`

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: gulp build

    - name: Verify dist folder
      run: ls -la dist

    - name: Deploy 'dist' to master branch
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_BLOG_TOKEN }}
        src_path: dist/.
        dst_path: /.
        dst_owner: greybax
        dst_repo_name: greybax.github.io
        src_branch: premaster
        dst_branch: master
        clean: true